move: ["+"] [beetle "x"] piece [[location "-"] location]

location: piece [neighbour_reference]

neighbour_reference: piece ["(" neighbour_reference ")"] [angle]

piece: "Q" | "q" | "G" | "g" | "A" | "a" | "S" | "s" | beetle
beetle: "B" | "b"

angle: "1" | "2" | "3" | "4" | "5"
